FROM eclipse/ubuntu_python:2.7

ENV PLATFORMIO_HOME_DIR /projects/.platformio
# After 3.2 release replace with sudo  pip install -U platformio
RUN sudo pip install https://github.com/platformio/platformio/archive/develop.zip
