FROM codenvy/ubuntu_python:2.7
# After 3.2 release replace with sudo  pip install -U platformio
RUN sudo pip install https://github.com/platformio/platformio/archive/develop.zip
WORKDIR /projects

CMD tail -f /dev/null
