FROM codenvy/ubuntu_python:2.7
RUN sudo apt-get update && sudo apt-get -y install python-pip
# After 3.2 release replace with sudo  pip install -U platformio
RUN sudo pip install https://github.com/platformio/platformio/archive/develop.zip
